### ISSUE TITLE
Request for docs: How to handle ENUM?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#197] opened 2016-09-03 17:02 UTC
Couldn't find how to handle ENUMs in the tutorial docs. How do I make `tenant_status` in the following schema an ADT in Opaleye?

```
create type tenant_status as enum('active', 'inactive');
create table tenants(
       id serial primary key
       ,created_at timestamp without time zone not null default current_timestamp
       ,updated_at timestamp without time zone not null default current_timestamp
       ,name text not null
       ,status tenant_status not null default 'inactive'
       ,owner_id integer
       ,backoffice_domain text not null
       constraint ensure_not_null_owner_id check (tenent_status!='active' or owner_id is not null)
);
```

**Comment by matsumonkie** [comment] 2016-09-07 04:55
Say you have:
```
data Gender = Female | Male deriving (Eq, Show, Generic)

data User' a = User'
  {  usrGender :: a
  } deriving (Eq, Show, Generic)

type User = User' (Gender)
type RUserColumn = User' (Column PGText)
type WUserColumn = User' (Column PGText)

```

One way to have your usrGender attribute parsed from PG to your code is by having `Gender` override `FromField ` and `QueryRunnerColumnDefault`:

```
instance FromField (Gender) where
  fromField f mdata =
    return gender
    where
      gender = case mdata of
        Just "female" -> Female
        Just "male" -> Male
        _ -> Male

instance QueryRunnerColumnDefault PGText Gender where
  queryRunnerColumnDefault = fieldQueryRunnerColumn
```

So for your example, I guess you need to do the same with but with your enum type.
There are other [possible ways](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/RunQuery.hs#L121-L141) to deal with this case

**Comment by saurabhnanda** [comment] 2016-09-11 14:04
Thanks @matsumonkie this solved my problem.

**Comment by matsumonkie** [comment] 2016-09-12 04:34
You're welcome ;-)

**Comment by saurabhnanda** [comment] 2016-09-25 16:47
@matsumonkie @tomjaguarpaw do you know how to set-up the default Haskell => PG mapping for ENUMS? I managed to get the following:

```
instance ToField TenantStatus where
  toField ts = case ts of
    TenantActive -> toField "active"
    TenantInactive -> toField "inactive"
    TenantNew -> toField "new"
```

but I'm unable to figure out how to get Opalaye to use it:

```
activateTenant :: TenantId -> AppM (Tenant)
activateTenant tenantId@(TenantId tid) = do
  conn <- askDbConnection
  liftIO $ do 
    _ <- runUpdate conn tenantTable
      -- ERROR: Couldn't match type ‘Column PGText’ with ‘Database.PostgreSQL.Simple.ToField.Action’
      (\tenant -> (tenantPGReadToWrite tenant) & status .~ toField TenantActive)
      -- (\tenant -> tenantPGReadToWrite tenant)
      (\tenant -> (tenant ^. key .== pgInt8 tid))
    head <$> runQuery conn (tenantById tenantId)
```

**Comment by tomjaguarpaw** [comment] 2016-09-25 16:50
I don't think Opaleye uses `ToField`.  I don't even remember knowing that existed.  Don't you want a `Constant` instance instead?

**Comment by tomjaguarpaw** [comment] 2016-09-25 16:50
(Perhaps `Constant` should use `ToField`)

**Comment by saurabhnanda** [comment] 2016-09-25 17:47
>  Don't you want a Constant instance instead?

How do I use `Constant` in the code I mentioned above?

**Comment by tomjaguarpaw** [comment] 2016-09-25 20:18
You'd write `constant TenantActive` instead of `toField TenantActive`.  But in this case you don't really win much since you have to implement the `Constant` instance by hand anyway.  It would be pretty much the same as your `ToField` instance.

**Comment by tomjaguarpaw** [comment] 2016-12-05 08:46
Actually I prefer this implementation of `FromField`

````
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE DeriveDataTypeable    #-}

import Opaleye
import Database.PostgreSQL.Simple.FromField
import Data.Typeable

data Gender = Female | Male deriving Typeable

instance FromField (Gender) where
  fromField f mdata = fromField f mdata >>= parseGender
    where parseGender genderString = case genderString of
            "female" -> return Female
            "male"   -> return Male
            _        -> returnError ConversionFailed f ("Unexpected gender: " ++ genderString)

instance QueryRunnerColumnDefault PGText Gender where
  queryRunnerColumnDefault = fieldQueryRunnerColumn
````

**Comment by saurabhnanda** [comment] 2016-12-05 08:49
```
instance QueryRunnerColumnDefault PGText Gender where
  queryRunnerColumnDefault = fieldQueryRunnerColumn
```

What if the gender column is implemented as under in Postgres:

```
create type gender as enum('male', 'female');
```

**Comment by tomjaguarpaw** [comment] 2016-12-05 08:50
> What if the gender column is implemented as under in Postgres:

I corrected that oversight.  It now maps from `PGGender` not `PGText`.

**Comment by sras** [comment] 2016-12-06 03:57
@tomjaguarpaw How would you implement the instance for, `Default Constant Gender (Column PGGender)`. This is required if if we want to save this type to the db right?

**Comment by tomjaguarpaw** [comment] 2016-12-06 08:18
````
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE DeriveDataTypeable    #-}
{-# LANGUAGE FlexibleInstances     #-}

import Data.Typeable
import Database.PostgreSQL.Simple.FromField
import Data.Profunctor.Product.Default
import Data.Profunctor
import Opaleye

data Gender = Female | Male deriving Typeable
data PGGender

instance FromField (Gender) where
  fromField f mdata = fromField f mdata >>= parseGender
    where parseGender genderString = case genderString of
            "female" -> return Female
            "male"   -> return Male
            _        -> returnError ConversionFailed f ("Unexpected gender: " ++ genderString)

instance QueryRunnerColumnDefault PGText Gender where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

constantColumnUsing :: Constant haskell (Column pgType)
                    -> (haskell' -> haskell)
                    -> Constant haskell' (Column pgType')
constantColumnUsing oldConstant f = dimap f unsafeCoerceColumn oldConstant

instance Default Constant Gender (Column PGGender) where
  def = constantColumnUsing (def :: Constant String (Column PGText)) genderToString

    where genderToString :: Gender -> String
          genderToString gender = case gender of
            Male   -> "male"
            Female -> "female"
````

**Comment by tomjaguarpaw** [comment] 2016-12-06 08:18
I added the `Default Constant` instance.

**Comment by sras** [comment] 2016-12-08 11:22
@tomjaguarpaw 

Thanks. This seem to be exactly what I was looking for.

But Is it alright to implement the Default Constant instance like the following without using the dimap function and constantColumnUsing function?

instance Default Constant Gender (Column PGGender) where
  def = Constant (unsafeCoerceColumn.pgStrictText.genderToString)
    where genderToString :: Gender -> T.Text
          genderToString gender = case gender of
            Male   -> "male"
            Female -> "female"

**Comment by tomjaguarpaw** [comment] 2016-12-08 13:07
It's fine I guess.

**Comment by tomjaguarpaw** [comment] 2016-12-08 13:09
It's probably more hygenic if you don't use the details of the `Constant` constructor but you can if you really want to.

**Comment by centromere** [comment] 2017-07-12 21:21
@tomjaguarpaw In the Gender data type above, why did you specify `deriving Typeable`?

**Comment by tomjaguarpaw** [comment] 2017-07-13 09:21
I don't remember for certain, but I presume it was because [`returnError` requires `Typeable`](http://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple-FromField.html#v:returnError).

**Comment by centromere** [comment] 2017-07-13 11:06
Interesting. I was able to compile code in which my data type does not derive `Typeable`, so I'm not sure what's going on:

```haskell
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE OverloadedStrings #-}
module App.Database.MembershipLevel where

import Data.Profunctor.Product.Default
import Data.Profunctor
import Data.Text (Text)
import Database.PostgreSQL.Simple.FromField
import Opaleye

data MembershipLevel
  = Monthly
  | Annual
  | Lifetime

data PGMembershipLevel

instance QueryRunnerColumnDefault PGMembershipLevel MembershipLevel where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

instance FromField MembershipLevel where
  fromField f mdata
    | mdata == Nothing         = returnError UnexpectedNull f ""
    | mdata == Just "monthly"  = return Monthly
    | mdata == Just "annual"   = return Annual
    | mdata == Just "lifetime" = return Lifetime
    | otherwise               = returnError ConversionFailed f ""

instance Default Constant MembershipLevel (Column PGMembershipLevel) where
  def = dimap levelToText unsafeCoerceColumn (def :: Constant Text (Column PGText))
    where
      levelToText :: MembershipLevel -> Text
      levelToText Monthly  = "monthly"
      levelToText Annual   = "annual"
      levelToText Lifetime = "lifetime"

main :: IO ()
main = return ()
```

Compiled with:
`stack --resolver lts-8.22 script MembershipLevel.hs`

**Comment by tomjaguarpaw** [comment] 2017-07-13 12:24
Are you using GHC 8.0?  As far as I can tell `AutoDeriveTypeable` is on by default in GHC 8.0.  In fact, perhaps you can't even turn it off.

**Comment by centromere** [comment] 2017-07-13 12:30
I am. I didn't know about `AutoDeriveTypeable`. That would certainly explain it!.\

**Comment by reygoch** [comment] 2018-03-04 18:03
@tomjaguarpaw sorry for bringing this up from history but I'd just like to know what is recommended way of creating new DB entries that use enums with this method.

I'd like to do something like this `insertUser` function, assuming all required instances are available for my enum type:

```
data UserType = Admin | Regular
data PGUserType
...
type UserW = User'
  (UserIDM)
  (Column PGUserType)
  (Column PGText)
  (Column PGText)
...

insertUser :: IO ()
insertUser = do
  conn <- connect connectInfo
  runInsertMany conn userT [( User (UserID Nothing) Regular "Username" "Password" )]
  pure ()
```

But obviously I can't pass in `Regular` since the expected type is `Column PGUserType` and I'm not sure how to "cast" my `UserType` to `PGUserType` in this case. Frankly it doesn't make any sense to me at the moment and things are getting a bit more verbose the more I try to make things type safe.

I will compile a little tutorial on some things that I think are lacking once I've figured out all of the pieces.

**Comment by tomjaguarpaw** [comment] 2018-03-04 22:54
> @tomjaguarpaw sorry for bringing this up from history

That's absolutely fine.  Feel free to ask any questions about anything!

> I'd just like to know what is recommended way of creating new DB entries that use enums with this method.

I don't think there is any recommended way.  I contented myself with the fact that it was *possible* and hoped a consensus would develop amongst users about the best way to deal with this kind of thing.  I don't think we made any progress though.

> I'd like to do something like this insertUser function, assuming all required instances are available for my enum type
>
> But obviously I can't pass in Regular since the expected type is Column PGUserType and I'm not sure how to "cast" my UserType to PGUserType in this case. Frankly it doesn't make any sense to me at the moment and things are getting a bit more verbose the more I try to make things type safe.

Let's start with something simple and see if we can improve it.  Does the following work?

    runInsertMany conn userT [( User (UserID Nothing) (unsafeCast "user_type" (pgString "regular")) "Username" "Password" )]

(where `user_type` is the name of your enum type and `'regular'` is the value of your enum type).  If that works then we can try to make it more type safe.  If it doesn't work then we'll try to fix it.

> I will compile a little tutorial on some things that I think are lacking once I've figured out all of the pieces.

That would be great.  The more input I have from different people using Opaleye the more I can improve the library or the documentation.

**Comment by reygoch** [comment] 2018-03-07 15:47
@tomjaguarpaw sorry for the late reply. That example doesn't work, I get the following SQL error:

```
*** Exception: SqlError {sqlState = "42704", sqlExecStatus = FatalError, sqlErrorMsg = "type \"usertype\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```

My enum is defined like this:

```
create type cookster."UserType" as enum ('Admin', 'Regular');
```

with explicitly stated schema, though that shouldn't matter because user that is accessing the DB has the same name. It seems like `unsafeCast` is lowercasing my enum name for some reason.

Here is the exact Haskell code that is being executed

```
insertUser :: IO ()
insertUser = do
  conn <- connect connectInfo
  runInsertMany conn userT $
    [( User (UserID Nothing) (unsafeCast "UserType" $ pgString "Regular") "Simple Joe 2" "SomePassword" )]
  -- runInsertMany conn userT [( User (UserID Nothing) "Regular" "Simple Joe" "SomePassword" )]
  pure ()
```

**Comment by tomjaguarpaw** [comment] 2018-03-07 15:53
Ah, I think we need to emit types in quotes.  Can you change [`ppSqlExpr`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/2efeddc4ac2c91dd91e1df624efc156ca85e1dfb/src/Opaleye/Internal/HaskellDB/Sql/Print.hs#L147) to

```haskell
    CastSqlExpr typ e -> text "CAST" <> parens (ppSqlExpr e <+> text "AS" <+> doubleQuotes (text typ))
```

i.e. add a `doubleQuotes`.

**Comment by tomjaguarpaw** [comment] 2018-03-07 15:55
(In an earlier version we had a similar problem for column names.  See https://github.com/tomjaguarpaw/haskell-opaleye/commit/3d9946f3f9ea912aa320ed7908357fe3a62dad5f)

**Comment by tomjaguarpaw** [comment] 2018-03-07 15:56
(And table names.  See https://github.com/tomjaguarpaw/haskell-opaleye/commit/597c729d2857ff2a38c5fa41a3502b95d40a54ff)

**Comment by reygoch** [comment] 2018-03-07 15:58
@tomjaguarpaw Ok, I'll do the pull request when I'm done. Give me just 10 min till I fork the project and make the changes.

**Comment by reygoch** [comment] 2018-03-07 16:13
I'm having trouble with compiling the project. There is something wrong with `Opaleye.Internal.Table` module.

```
C:\Users\reygoch\Documents\Projects\haskell-opaleye\src\Opaleye\Internal\Table.hs:125:39: error:
    Not in scope: type variable `a'
```

Something popped up now so I'll finish up once I get back home.

**Comment by tomjaguarpaw** [comment] 2018-03-07 17:34
The latest `master` was broken, sorry.  You can try from 096a9b3ae18077bfbbcabb71b9a017ada0a1f8c9 or you can wait until I merge https://github.com/tomjaguarpaw/haskell-opaleye/tree/tomjaguarpaw-patch-1 into `master`.

**Comment by tomjaguarpaw** [comment] 2018-03-07 17:40
`master` is now fixed.

**Comment by reygoch** [comment] 2018-03-07 20:38
@tomjaguarpaw I've sent the pull request and now everything works fine on my end, but it seems like that change breaks some tests on travis.

**Comment by tomjaguarpaw** [comment] 2018-03-07 22:20
OK thanks.  Let's discuss the test failure on the PR.

**Comment by tomjaguarpaw** [comment] 2018-03-08 10:45
Now that we an approach to enums that works for you (even if arrays are not yet fixed...) shall we discuss your impressions of it and how to improve it?

**Comment by reygoch** [comment] 2018-03-08 11:24
Sure. Initial problem was that I did not quite understand how above mentioned [way](https://github.com/tomjaguarpaw/haskell-opaleye/issues/197#issuecomment-265088228) is supposed to be used in practice, since I can't just do something like this because it doesn't type check.

```
data UserType = Admin | Regular
data PGUserType
...
type UserW = User'
  (UserIDM)
  (Column PGUserType)
  (Column PGText)
  (Column PGText)
...

insertUser :: IO ()
insertUser = do
  conn <- connect connectInfo
  runInsertMany conn userT [( User (UserID Nothing) Regular "Username" "Password" )]
  pure ()
```

I'm assuming there is some `misteryFunction` that I can wrap `Regular` with to convert it to appropriate type like this:

```
...
  runInsertMany conn userT [( User (UserID Nothing) (mysteryFunction Regular) "Username" "Password" )]
...
```

But that is getting a bit cluttered now, especially since I can't just put `Nothing` instead of `UserID` (which is autoincrementing ID). A few more of such peculiar fields and it will become quite cumbersome to work with data.

Ideally I'd be able to do just this:

```
  runInsertMany conn userT [( User Nothing Regular "Username" "Password" )]
```

And things will be handled for me in the background. I'm guessing that such enum handling can be achieved by this `Default` typeclass but I don't quite understand how at the moment so I'd appreciate a nudge in the right direction.

**Comment by tomjaguarpaw** [comment] 2018-03-08 15:08
Here's the next iteration.  It is a complete solution.  Let me know your thoughts and we'll iterate on this.  (NB the way of dealing with `UserID Nothing` is still a huge pain but let's tackle that separately.)

```
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell #-}

import Data.Typeable
import Data.Maybe
import Opaleye
import Opaleye.Constant
import Database.PostgreSQL.Simple.FromField hiding (tableColumn)
import Data.Profunctor
import Data.Profunctor.Product.Default
import Data.Profunctor.Product.TH

-- Schema stuff

data User' a b c d = User { userId :: a, userType :: b, userUsername :: c, userPassword :: d }
data UserID' a = UserID a

$(makeAdaptorAndInstance' ''User')
$(makeAdaptorAndInstance' ''UserID')

data UserType = Admin | Regular
data PGUserType

type UserW = User'
             (UserIDM)
             (Column PGUserType)
             (Column PGText)
             (Column PGText)

type UserR = User'
             (UserID)
             (Column PGUserType)
             (Column PGText)
             (Column PGText)

type UserIDM = UserID' (Maybe (Column PGInt4))
type UserID  = UserID' (Column PGInt4)

userT :: Table UserW UserR
userT = table "User" $ pUser User
  { userId       = pUserID $ UserID $ tableColumn "id"
  , userType     = tableColumn "type"
  , userUsername = tableColumn "username"
  , userPassword = tableColumn "password"
  }

-- The stuff you have to do to set up UserType

userTypeMapper :: EnumMapper UserType PGUserType
userTypeMapper = EnumMapper {
    enumToHaskell = \s -> case s of
       "admin"   -> Just Admin
       "regular" -> Just Regular
       _         -> Nothing
  , haskellToEnum = \h -> case h of
       Admin   -> "admin"
       Regular -> "regular"
  }

instance Default Constant UserType (Column PGUserType) where
  def = constantEnum userTypeMapper

instance FromField UserType where
  fromField = fromFieldEnum userTypeMapper

instance QueryRunnerColumnDefault PGUserType UserType where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

-- How you use the UserType Constant instance

foo conn = runInsertMany conn userT
             [ constant (User (UserID (Nothing :: Maybe Int)) Regular "Username" "Password") ]

-- Library code
                                                                                                                                                  d
ata EnumMapper a sqlType = EnumMapper {
    enumToHaskell :: String -> Maybe a
  , haskellToEnum :: a -> String
  }

fromFieldEnum :: Typeable a
              => EnumMapper a pgType
              -> FieldParser a
fromFieldEnum s2h f mdata = fromField f mdata >>= parse
  where parse string = case (enumToHaskell s2h) string of
          Nothing -> returnError ConversionFailed f ("Unexpected enum value: " ++ string)
          Just h  -> return h

constantEnum :: EnumMapper a sqlType -> Constant a (Column sqlType)
constantEnum h2s = dimap (haskellToEnum h2s) unsafeCoerceColumn def_
  where def_ :: Constant String (Column PGText)
        def_ = def
```

**Comment by reygoch** [comment] 2018-03-10 11:42
@tomjaguarpaw I've been testing your suggested solution, and there have been a few problems, so I think I'm just going to stick with smart constructors for now that will handle conversion from Enums to Text / PGText for me.

First problem is that things are getting quite cluttered, which I don't really like.

Second is that I've discovered that TH "splits" code evaluation every time it is called. So if I have something like :

```
userTypeMapper :: EnumMapper UserType PGUserType
...
$(makeAdaptorAndInstance' ''UserID')
...
data EnumMapper a sqlType
...
```
my code doesn't work and `EnumMapper` has to be defined before the TH split if I'm using it in the code before. This particular case would be solved if EnumMapper was included in the library, but still it's kind of messy.

And last problem that I've found is that for some reason your example doesn't work for me:

```
runInsertMany conn userT
    [ constant (User (UserID (Nothing :: Maybe Int)) Regular "NewTest" "Password") ]
```

I get the following error:

```
    * Ambiguous type variable `password0' arising from the literal `"SomePassword"'
      prevents the constraint `(Data.String.IsString
                                  password0)' from being solved.
      Probable fix: use a type annotation to specify what `password0' should be.
      These potential instances exist:
        instance [safe] Opaleye.Internal.Column.PGString a =>
                        Data.String.IsString (Column a)
          -- Defined at C:\Users\reygoch\Documents\Projects\haskell-opaleye\src\Opaleye\Internal\Column.hs:91:10
        instance Data.String.IsString Database.PostgreSQL.Simple.Query
          -- Defined in `Database.PostgreSQL.Simple.Types'
        instance a ~ Char => Data.String.IsString [a]
          -- Defined in `Data.String'
        ...plus 28 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    * In the fourth argument of `User', namely `"SomePassword"'
      In the first argument of `constant', namely
        `(User (UserID Nothing) (Regular) "New Test" "SomePassword")'
      In the expression:
        constant
          (User (UserID Nothing) (Regular) "New Test" "SomePassword")
   |
36 |     [constant ( User (UserID Nothing) (Regular) "New Test" "SomePassword" )]
   |                                                            ^^^^^^^^^^^^^^
```

**Comment by tomjaguarpaw** [comment] 2018-03-15 11:01
OK, thanks for letting me know.

> First problem is that things are getting quite cluttered, 

Could you explain exactly what it is that you consider to be clutter?

>Second is that I've discovered that TH "splits" code evaluation every time it is called

Yes, this is one of the artifacts of TH.  I think the problem is solved entirely by having `EnumMapper` in the library.  What makes you think it would continue to be messy if that happened?

> And last problem that I've found is that for some reason your example doesn't work for me

Is it because you have `OverloadedStrings` on?

**Comment by hgrano** [comment] 2018-05-19 07:30
@tomjaguarpaw I can get your last example to work for insertion, but not for querying. I have an underlying Postgres user type:

`CREATE TYPE usert AS ENUM('admin', 'regular');`

I've taken your previous example but added 

`type UserRHaskells =  User'
                     (UserID' Int)
                     UserType
                     Text
                     Text

userQuery :: Query UserR
userQuery = queryTable userT

runUserQuery :: Connection -> IO [UserRHaskells]
runUserQuery conn = runQuery conn userQuery`

When I run `runUserQuery` I get an error: `Incompatible {errSQLType = "usert", errSQLTableOid = Just (Oid 33432), errSQLField = "result2_2", errHaskellType = "Text", errMessage = "types incompatible"}`. How can I get this working?

**Comment by tomjaguarpaw** [comment] 2018-05-19 08:13
Can you show me your `instance FromField UserType`?  I don't understand why it mentions `Text` when, if you are using the instance I gave above, it should be `String`.

In any case, I think my instance is wrong.  It should be more like https://stackoverflow.com/a/38429920/997606

**Comment by hgrano** [comment] 2018-05-20 02:56
@tomjaguarpaw the issue wasn't to do with `Text`. 

> In any case, I think my instance is wrong. It should be more like https://stackoverflow.com/a/38429920/997606

I tried this, but was unable to get that working. Instead I replaced your `fromFieldEnum` as follows:

```haskell
fromFieldEnum :: Typeable a
              => EnumMapper a pgType
              -> FieldParser a
fromFieldEnum s2h f mdata =
  case mdata of
    Just bStr ->
      let str = unpack bStr in
      case enumToHaskell s2h str of
        Just h -> return h
        Nothing -> returnError ConversionFailed f ("Unexpected enum value: " ++ str)
    Nothing -> returnError ConversionFailed f "Unexpected empty value"
```
This worked for insertion and querying.

**Comment by tomjaguarpaw** [comment] 2018-05-20 07:08
That's great!  Did you need to change anything else in my code above?  I should make a module out of this.

**Comment by hgrano** [comment] 2018-05-20 09:17
No there was nothing else I changed. The full example with my changes:
```haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE Arrows #-}

module TestEnum where


import Data.Typeable
import Opaleye
import Database.PostgreSQL.Simple.FromField hiding (tableColumn)
import Database.PostgreSQL.Simple (Connection)
import Data.Profunctor
import Data.Profunctor.Product.Default
import Data.Profunctor.Product.TH
import Data.Int (Int64)
import Data.ByteString.Char8 (unpack)
-- Schema stuff

data User' a b c d = User { userId :: a, userType :: b, userUsername :: c, userPassword :: d }
data UserID' a = UserID a

$(makeAdaptorAndInstance' ''User')
$(makeAdaptorAndInstance' ''UserID')

data UserType = Admin | Regular deriving (Eq, Ord, Show)
data PGUserType

type UserW = User'
             (UserIDM)
             (Column PGUserType)
             (Column PGText)
             (Column PGText)

type UserR = User'
             (UserID)
             (Column PGUserType)
             (Column PGText)
             (Column PGText)

type UserIDM = UserID' (Maybe (Column PGInt4))
type UserID  = UserID' (Column PGInt4)

userT :: Table UserW UserR
userT = table "users" $ pUser User
  { userId       = pUserID $ UserID $ tableColumn "id"
  , userType     = tableColumn "type"
  , userUsername = tableColumn "username"
  , userPassword = tableColumn "password"
  }

-- The stuff you have to do to set up UserType

userTypeMapper :: EnumMapper UserType PGUserType
userTypeMapper = EnumMapper {
    enumToHaskell = \s -> case s of
       "admin"   -> Just Admin
       "regular" -> Just Regular
       _         -> Nothing
  , haskellToEnum = \h -> case h of
       Admin   -> "admin"
       Regular -> "regular"
  }

instance Default Constant UserType (Column PGUserType) where
  def = constantEnum userTypeMapper

instance FromField UserType where
  fromField = fromFieldEnum userTypeMapper

instance QueryRunnerColumnDefault PGUserType UserType where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

-- How you use the UserType Constant instance
runInsertUser :: Connection -> IO Int64
runInsertUser conn = runInsertMany conn userT
                                   [ constant (User (UserID (Nothing :: Maybe Int)) Regular "Username" "Password") ]
type UserRHaskells =  User'
                     (UserID' Int)
                     UserType
                     String
                     String

userQuery :: Query UserR
userQuery = queryTable userT

runUserQuery :: Connection -> IO [UserRHaskells]
runUserQuery conn = runQuery conn userQuery

-- Library code

data EnumMapper a sqlType = EnumMapper {
    enumToHaskell :: String -> Maybe a
  , haskellToEnum :: a -> String
}

fromFieldEnum :: Typeable a
              => EnumMapper a pgType
              -> FieldParser a
fromFieldEnum s2h f mdata =
  case mdata of
    Just bStr ->
      let str = unpack bStr in
      case enumToHaskell s2h str of
        Just h -> return h
        Nothing -> returnError ConversionFailed f ("Unexpected enum value: " ++ str)
    Nothing -> returnError ConversionFailed f "Unexpected empty value"

constantEnum :: EnumMapper a sqlType -> Constant a (Column sqlType)
constantEnum h2s = dimap (haskellToEnum h2s) unsafeCoerceColumn def_
  where def_ :: Constant String (Column PGText)
        def_ = def
```

**Comment by pjones** [comment] 2019-10-24 23:47
FWIW I had to use `unsafeCast "enum-type"` instead of `unsafeCoerceColumn` otherwise PostgreSQL would give me an error:

```
sqlErrorMsg = "column \"key_use\" is of type key_use_t but expression is of type text",
sqlErrorHint = "You will need to rewrite or cast the expression."
```

**Comment by tomjaguarpaw** [comment] 2019-10-25 13:51
Yes, I think `unsafeCast` makes more sense her actually, since it actually attaches the type to the generated SQL.

**Comment by tuomohopia** [comment] 2020-02-06 21:00
I just started building my schema with Opaleye, is that example a good reflection of how to set up enums now in Postgres?

**Comment by tomjaguarpaw** [comment] 2020-02-07 17:49
I believe this is the best way for doing enums in Opaleye at the moment.  It would be good to gather feedback from people who have done it this way and build a nice API around this.

**Comment by pjones** [comment] 2020-02-07 19:18
For anyone who is curious, this is what I've been doing:

```haskell
--------------------------------------------------------------------------------
-- | What a key can be used for.
data KeyUse = Sig | Enc
  deriving (Generic, Show, Eq, ToJSON, FromJSON)

--------------------------------------------------------------------------------
-- | For table definitions:
data SqlKeyUse

--------------------------------------------------------------------------------
-- | Convert a 'KeyUse' to 'Text'.
fromKeyUse :: KeyUse -> Text
fromKeyUse = Text.toLower . show

--------------------------------------------------------------------------------
-- | Convert a 'Text' to a 'KeyUse'.
toKeyUse :: (MonadPlus m) => Text -> m KeyUse
toKeyUse "sig" = pure Sig
toKeyUse "enc" = pure Enc
toKeyUse _     = mzero

--------------------------------------------------------------------------------
instance FromField KeyUse where
  fromField f mdata =
    case mdata of
      Just bs -> toKeyUse (decodeUtf8 bs)
      Nothing -> returnError ConversionFailed f "Unexpected empty value"

instance QueryRunnerColumnDefault SqlKeyUse KeyUse where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

instance Default Constant KeyUse (Column SqlKeyUse) where
  def = dimap fromKeyUse (unsafeCast "key_use_t") def_
    where def_ :: Constant Text (Column SqlText)
          def_ = def
```

**Comment by jaredramirez** [comment] 2020-11-17 20:15
@pjones's solution works for me, with minor updates for `0.7`:

```haskell
instance QueryRunnerColumnDefault SqlKeyUse KeyUse where
  queryRunnerColumnDefault = fieldQueryRunnerColumn
-->
instance DefaultFromField SqlKeyUse KeyUse where
  defaultFromField = fieldQueryRunnerColumn


instance Default Constant KeyUse (Column SqlKeyUse) where
  ...
-->
instance (field ~ (Field SqlKeyUse)) => Default ToFields KeyUse field where
  ...
```

**Comment by tomjaguarpaw** [comment] 2020-11-17 20:55
There is now rough experimental support for this in [Opaleye.Enum](https://hackage.haskell.org/package/opaleye-0.7.1.0/docs/Opaleye-Experimental-Enum.html). You can [see an example usage](https://github.com/tomjaguarpaw/2020-munihac-opaleye-workshop/blob/5234a972aafe0e2980a3eb47b5c08ffcf56295f4/Types/Film.hs#L21-L66).

**Comment by jaredramirez** [comment] 2020-11-19 16:51
`Opaleye.Experimental.Enum (fromFieldToFieldsEnum)` is awesome! Makes it super easy.

I also was able to use `fromFieldToFieldsEnum` for [domains](https://www.postgresql.org/docs/9.5/sql-createdomain.html), so might be worth generalized the name/module in the future.

**Closed** 2021-02-05 20:57 UTC

**Comment by tomjaguarpaw** [comment] 2021-02-07 16:34
I'm considering this closed now that [`Opaleye.Experiemental.Enum`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/f5d6e9ab4b75f3b5ba46fe6e7bb88df35a2e398c/src/Opaleye/Experimental/Enum.hs) exists. The API in `master` is very nice. I haven't made a Hackage release yet but anyone is welcome to ask for one if they would like one.
