### ISSUE TITLE
runQuery causes "Segmentation fault/access violation in generated code"

### ISSUE THREAD

**Issue by JBetz** [tomjaguarpaw/haskell-opaleye#338] opened 2017-10-09 18:41 UTC
The `doTestSelectQuery` defined below is causing my application to crash and output the cryptic "Segmentation fault/access violation in generated code" error. The insert query works fine, however.

```haskell
module Main where

import           Data.Int
import           Data.Profunctor.Product    (p1)
import           Database.PostgreSQL.Simple (Connection, connect,
                                             connectDatabase, connectPassword,
                                             defaultConnectInfo)
import           Opaleye                    (Column, PGText, Query,
                                             Table (Table), queryTable,
                                             required, runInsertMany, runQuery)
import qualified Opaleye.PGTypes            as P

main :: IO ()
main = do
  connection <- connect $ defaultConnectInfo { connectDatabase = "postgres", connectPassword = "changeme"}
  r1 <- doTestInsertQuery connection
  print r1
  r2 <- doTestSelectQuery connection
  print r2

doTestInsertQuery :: Connection -> IO Int64
doTestInsertQuery connection =
  runInsertMany connection testTable [P.pgString "ok"]

doTestSelectQuery :: Connection -> IO [String]
doTestSelectQuery connection =
  runQuery connection testQuery

testQuery :: Query (Column PGText)
testQuery =
  queryTable testTable

testTable :: Table (Column PGText) (Column PGText)
testTable =
  Table "test" (p1 (required "message"))
```

I also rebuilt it with GHC 8.2.1, and it failed at the same location, but the error message was slightly more informative: "Access violation in generated code when executing data at 000000008000fb90".

Edit: minimizing dependencies, initial snippet (minus TH) [is here](http://lpaste.net/359227)

---

OS: Windows 10
CPU: x64
GHC: 8.02
Opaleye: 0.5.4.0
Postgres: 10

**Comment by tomjaguarpaw** [comment] 2017-10-09 19:58
That's very strange indeed, but a TemplateHaskell/GHC bug, not an Opaleye bug!

**Comment by JBetz** [comment] 2017-10-09 20:24
Figured as much. So, the best next step would probably be to try eliminating the TH and rebuild. And if that fails, I guess it's a GHC problem?

**Comment by tomjaguarpaw** [comment] 2017-10-09 21:02
I guess you can compile with whatever GHC option it is that will dump the generated TH.  Then paste it into your source and recompile.

**Comment by JBetz** [comment] 2017-10-09 22:45
Same error without TH. I'm guessing it's caused by the C code generated by the underlying `postgresql-libpq` library.

**Comment by saurabhnanda** [comment] 2017-10-10 01:20
Just to eliminate one possible cause, can you try renaming the "timestamp"
column to anything else? "timestamp" is a core data type in PG.

On 10-Oct-2017 4:15 AM, "Joe Betz" <notifications@github.com> wrote:

Same error without TH. I'm guessing it's caused by the C code generated by
the underlying postgresql-libpq library.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomjaguarpaw/haskell-opaleye/issues/338#issuecomment-335310134>,
or mute the thread

**Comment by saurabhnanda** [comment] 2017-10-10 01:23
Also, what's the code for C.fromRow? Please put Debug.Trace calls after
every line in the allCellsQuery function to narrow down the exact line of
code causing the crash.

**Comment by JBetz** [comment] 2017-10-10 01:32
I tried renaming the timestamp field to aTimestamp, and it still failed. 

Here's what `allCellsQuery` looks like with `trace` calls:

```haskell
allCellsQuery :: Connection -> IO [C.Cell]
allCellsQuery connection = do
  cells <- runQuery (trace "beforeRunQuery" connection) (queryTable (trace "beforeQueryTable" cellTable))
  pure $ fmap fromRow (trace "before fromRow" cells)
```

And here's what it outputs:
```
beforeRunQuery
beforeQueryTable
Segmentation fault/access violation in generated code
```

C.fromRow just takes a CellRecordResult and returns a Cell. So basically, converts it between the database type and my model type. And as the logs show, it isn't even being run.

**Comment by saurabhnanda** [comment] 2017-10-10 01:34
Please turn on SQL logging in PG to see if the generated SQL is even being
sent to PG or not. Please share the generated SQL if it is showing up in
the logs.

**Comment by JBetz** [comment] 2017-10-10 01:45
Here's what I'm seeing in logs:

'2017-10-09 20:43:31.328 CDT [37664] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.'

Which makes sense.

**Comment by saurabhnanda** [comment] 2017-10-10 02:18
Time to dig deeper into pg-simple. Care to put a bunch of debug/trace
statements within pg-simple?

**Comment by JBetz** [comment] 2017-10-10 03:12
I'm not particularly invested in `opaleye` right now, it's just part of my survey of what the different options are for interacting with Postgres in Haskell. At this point I'd rather move forward with a different library than spend a lot of time trying to debug what is most likely a very low level problem. I agree that this seems like the best next step, but I don't have the time for it right now. If it is an issue in `pg-simple` or lower, then I guess I'll have to deal with it at some point. I'm going to reimplement what I already have with `persistent` and see if anything similar happens.

Also, littering `pg-simple` with trace statements sounds like a pain. Are there any tools for getting the call stack from a specific location? Or trace logging in general? A log with indentation + module name + function / value name + timestamp would be great, but I've yet to find anything like that for Haskell.

**Comment by saurabhnanda** [comment] 2017-10-10 03:38
I feel your pain.

Can you try doing this on a Linux machine? I didn't notice that you're on windows. My general **second hand** opinion is that Windows isn't supported as well as Linux in the Haskell ecosystem.

You can get proper stack traces only if your compile you entire package DB with profiling enabled. If not your entire package DB, then at least Opaleye and pg-simple.

**Comment by tomjaguarpaw** [comment] 2017-10-10 12:44
@JBetz Have you got a Template Haskell-free minimal code sample that you can share that causes a crash?

**Comment by tomjaguarpaw** [comment] 2017-10-10 12:46
@JBetz This bug report is the only thing I can find on Google matching "access violation in generated code when executing data": https://ghc.haskell.org/trac/ghc/ticket/13112.  It looks like it may only occur on 64-bit Windows.

Do you have code *without* TH that produces a similar error?

**Comment by JBetz** [comment] 2017-10-10 15:26
@saurabhnanda Yeah, I've run into a number of Windows issues. I'm the process of getting a Ubuntu VM set up on my computer, and once I do, I'll try running it there. As for stack traces, I tried compiling with profiling enabled and got no additional information, which suggests that Haskell isn't catching / handling it, and that it's happening on a lower layer.

**Comment by JBetz** [comment] 2017-10-10 15:29
@tomjaguarpaw That's what I found too, but I don't think the issue is with TH here. Like I already said, replacing the TH with the code generated by TH didn't fix it.

Here's what that looks like:

```haskell
import           Data.Profunctor.Product         (ProductProfunctor, (***$),
                                                  (****))
import           Data.Profunctor.Product.Default
import           Data.Profunctor.Product.TH      (makeAdaptorAndInstance)
import           Data.Profunctor.Unsafe

pCell :: forall p a1_0 a2_0 a3_0 a4_0 a5_0 a1_1 a2_1 a3_1 a4_1 a5_1. ProductProfunctor p
      => CellRecord (p a1_0 a1_1) (p a2_0 a2_1) (p a3_0 a3_1) (p a4_0 a4_1) (p a5_0 a5_1)
      -> p (CellRecord a1_0 a2_0 a3_0 a4_0 a5_0) (CellRecord a1_1 a2_1 a3_1 a4_1 a5_1)
pCell f =
  ((((CellRecord ***$ lmap id (id f))
    **** lmap contents (contents f))
      **** lmap notes (notes f))
        **** lmap author (author f))
          **** lmap timestamp (timestamp f)

instance ( ProductProfunctor p
         , Default p a1_0 a1_1
         , Default p a2_0 a2_1
         , Default p a3_0 a3_1
         , Default p a4_0 a4_1
         , Default p a5_0 a5_1)
        => Default p (CellRecord a1_0 a2_0 a3_0 a4_0 a5_0) (CellRecord a1_1 a2_1 a3_1 a4_1 a5_1) where
  def = pCell (CellRecord def def def def def)
```

**Comment by tomjaguarpaw** [comment] 2017-10-10 20:08
That generated code looks completely innocuous.  If you compile your program pasting these definitions in instead of using TD does the error message still refer to "generated code"?

**Comment by JBetz** [comment] 2017-10-10 20:37
Yes it's the exact same error message.

**Comment by tomjaguarpaw** [comment] 2017-10-10 20:49
Interesting.  Then I suspect "generated" does not apply to Template Haskell.

**Comment by tomjaguarpaw** [comment] 2017-10-10 20:50
All I can suggest at this point is coming up with a minimal example and reporting it on GHC Trac.

**Comment by JBetz** [comment] 2017-10-11 07:45
So, I just rewrote the same functionality with `persistent`, and am getting the exact same error. And there's a [corresponding issue ](https://github.com/yesodweb/persistent/issues/697) in that project as well. Given the low priority of the ticket, and overall poor support for Haskell on Windows, I'm planning to just switch to Linux at this point. Pretty surprised and disappointed at this situation. 

Nevertheless, I appreciate the help. :}

**Comment by tomjaguarpaw** [comment] 2017-10-11 10:10
That's interesting.  It may be a problem with generated code in `postgresql-libpq`.  If you're willing to make an absolutely minimal test case and add that to the Trac ticket that would be helpful for improving the state of Haskell on Windows.

**Comment by Mistuke** [comment] 2017-10-21 03:56
> Given the low priority of the ticket, and overall poor support for Haskell on Windows, I'm planning to just switch to Linux at this point. Pretty surprised and disappointed at this situation.

It's not that the ticket is low priority. It's just that the dependency chain for this report is so incredibly big that it's hard to figure out what's going on. I would be happy to take a look if I can get a repro with no stack requirement and it would be really handy if as many libraries can be removed as possible. I have to wade through assembly code here and the huge number of dependencies makes it time consuming..

Anyway, I have a suspicion of what it may be, If you can reliably reproduce the crash on your machine I can provide a build for you to test.

**Comment by JBetz** [comment] 2017-10-21 05:00
> Anyway, I have a suspicion of what it may be, If you can reliably reproduce the crash on your machine I can provide a build for you to test.

I can, so I'd be happy to try it out.

>  I would be happy to take a look if I can get a repro with no stack requirement and it would be really handy if as many libraries can be removed as possible. 

I stripped out all the layers on top of `postgresql-libpq` and used it directly to execute a statement that was semantically equivalent to what I was using `opaleye` to query for, but wasn't able to reproduce the crash. If it turns out to be unrelated to what you think it is, I'll continue the investigation. I'm fairly new to Haskell, and so having to learn a lot along the way. But I would like to help erase this flaw, since it's a fairly big one for Windows users.

Do you know if [hat](https://archives.haskell.org/projects.haskell.org/hat/) be any help for tracking an issue like this? That was going to be my next step.

> I have to wade through assembly code here and the huge number of dependencies makes it time consuming.

That's awful. :/

What surprises and disappoints me most is the lack of tool support for debugging, and I can't help but think it's a side-effect of the commitment to purity. I don't know what a properly Haskell solution would be, but there really needs to be one. Maybe just simple visualizations of call graphs, to start.

**Comment by tomjaguarpaw** [comment] 2017-10-21 08:44
> side-effect of the commitment to purity

**Comment by tomjaguarpaw** [comment] 2017-10-21 08:45
:)

**Comment by Mistuke** [comment] 2017-10-21 19:55
Hi,

Could anyone able to reliably reproduce this issue
try https://1drv.ms/u/s!AuQz_u-9HaJPmcQRFveWa9dMBi77hg ?

If you can still reproduce this issue with this build start with
+RTS --generate-crash-dumps

and send the dump it creates. Note that this is a pre-release version of GHC 8.4
so some packages may not compile without updating version bounds.

**Comment by JBetz** [comment] 2017-10-22 21:06
@Mistuke I've downloaded the ghc build, now how do I give stack the path to it?

**Comment by Mistuke** [comment] 2017-10-22 21:12
Sorry I don't use stack so don't know, but the documentation suggests a custom setup-info https://docs.haskellstack.org/en/stable/yaml_configuration/#setup-info

**Comment by JBetz** [comment] 2017-10-22 22:11
@Mistuke Okay, I was able to make stack use the custom build by adding it to $PATH and setting the system-ghc option to true. But it's still failing to compile because stack doesn't support that GHC version.

I'm told that the next best step is to try to eliminate stack and configure everything manually with cabal. If anyone could show me how to write the cabal file to run the code in the OP with the custom build, it would be much appreciated. Otherwise, I'll see what I can do.

**Comment by Mistuke** [comment] 2017-10-22 23:00
I would imagine that this should work, open a new cmd prompt in a folder you want,

```
set PATH=<path-to-ghc>;%PATH%
cabal sandbox init
cabal install opaleye
ghc <file>
```

**Comment by JBetz** [comment] 2017-10-22 23:28
That doesn't seem to work. Even with the custom build at the top of my path, `ghc -v` returns v8.0.2.

I also tried using the `--with-ghc`, but haven't been able to get that to work either.

```
cabal build --with-ghc="C:\Users\Joseph Betz\Downloads\ghc-8.3.20171021"
Warning: cannot determine version of C:\Users\Joseph
Betz\Downloads\ghc-8.3.20171021 :
""
Building postgres-debug-0.1.0.0...
Preprocessing executable 'postgres-debug' for postgres-debug-0.1.0.0...
C:\Users\Joseph Betz\Downloads\ghc-8.3.20171021: createProcess: permission
denied (Permission denied)
```

And if I point directly to the executable:

```
cabal build --with-ghc="C:\Users\Joseph Betz\Downloads\ghc-8.3.20171021\bin\ghc.exe"
Building postgres-debug-0.1.0.0...
Preprocessing executable 'postgres-debug' for postgres-debug-0.1.0.0...
C:\Users\Joseph Betz\Documents\Programming\Haskell\postgres-debug\.cabal-sandbox\x86_64-windows-ghc-8.0.2-packages.conf.d\package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
```

**Comment by JBetz** [comment] 2017-10-23 02:48
Okay, something must have been wrong with my path. I've got the correct ghc version running now, but it fails when trying to install `opaleye`:

`> cabal install opaleye
Resolving dependencies...
Notice: installing into a sandbox located at C:\Users\Joseph
Betz\Documents\Programming\Haskell\postgres-debug\.cabal-sandbox
Configuring opaleye-0.6.0.0...
Failed to install opaleye-0.6.0.0
Build log ( C:\Users\Joseph Betz\Documents\Programming\Haskell\postgres-debug\.cabal-sandbox\logs\opaleye-0.6.0.0.log ):
Configuring opaleye-0.6.0.0...
cabal.exe: ghc-pkg dump failed
cabal-tmp-3068\opaleye-0.6.0.0'
cabal: Leaving directory 'C:\Users\JOSEPH~1\AppData\Local\Temp\cabal-tmp-3068\opaleye-0.6.0.0'
cabal: Error: some packages failed to install:
opaleye-0.6.0.0 failed during the configure step. The exception was:
ExitFailure 1`

**Comment by Mistuke** [comment] 2017-10-23 21:17
Hmm what does the build log say?

**Comment by JBetz** [comment] 2017-10-23 22:39
```
Configuring opaleye-0.6.0.0...
cabal.exe: ghc-pkg dump failed
cabal-tmp-13500\opaleye-0.6.0.0'
cabal: Leaving directory 'C:\Users\JOSEPH~1\AppData\Local\Temp\cabal-tmp-13500\opaleye-0.6.0.0'

**Comment by Mistuke** [comment] 2017-10-23 22:43
Does 'ghc-pkg dump' work? It's possible the released cabal is not
compatible with it. I'll take a look tomorrow but I don't believe there was
an interface change

**Comment by tomjaguarpaw** [comment] 2017-11-13 11:14
Closing because I don't think this is an Opaleye issue.

**Closed by tomjaguarpaw** 2017-11-13 11:14 UTC
